The Basics


In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3],dtype='int32')

In [3]:
print(a)


[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get the Dimension
b.ndim

2

In [6]:
# Get the shape
b.shape

(2, 3)

In [7]:
# Get the type 
a.dtype

dtype('int32')

In [8]:
# Get size 
a.itemsize

4

In [9]:
# get total size 
a.size * a.itemsize 
a.nbytes # same as the above

12

Accessing/Changing specific element,row,column, etc

In [10]:
a2 = np.array([[1,2,3,4,5,6],[7,8,10,11,19,12]])
print(a2)

[[ 1  2  3  4  5  6]
 [ 7  8 10 11 19 12]]


In [11]:
# a2[row,col]
print(a2[0,4])


5


In [12]:
# specific row 
print(a2[0,4])

5


In [13]:
# get specific column 
print(a2[:,1])

[2 8]


In [14]:
# [row,start:end:step]
a2[0,1:6:2]

array([2, 4, 6])

In [15]:
# changing the element   
a2[1,2]=9
print(a2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 11 19 12]]


In [16]:
a2[0,:] = range(1,7)
a2[1,:] = range(7,13)
print(a2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
a2[:,:] = a2*a2

In [18]:
a2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144]])

In [19]:
a2[:,2] = [9,9]

In [20]:
a2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,   9, 100, 121, 144]])

# 3D Array

In [21]:
b = np.array([[[1,2],[2,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [2 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Get specific element
#[dimension,row,col]
b[0,1,0] = 3
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Initializing Different Types of Arrays 

In [23]:
# All zeros matrix
np.zeros(5)
np.zeros((2,3))
np.zeros((2,3,3),dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [24]:
# All 1s matrix
np.ones(5,dtype='int32')
np.ones((2,4),dtype="int32")
z = np.ones((2,3,2))
print(z.shape)

(2, 3, 2)


In [25]:
# Any other matrix
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [26]:
# Any other number(full_like)
np.full(b.shape,8)
np.full_like(b,8) # same as the above method 

array([[[8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8]]])

In [27]:
# Random decimal numbers 
np.random.random((4,2,3))
# or 
np.random.rand(4,2,3) # same as the above

array([[[0.11456256, 0.62884934, 0.87020208],
        [0.63666089, 0.98787954, 0.48761254]],

       [[0.64979335, 0.80346061, 0.10832111],
        [0.42414384, 0.80625806, 0.67935535]],

       [[0.84998957, 0.01720219, 0.08145812],
        [0.20369527, 0.39306894, 0.56059743]],

       [[0.78958403, 0.39130559, 0.82732355],
        [0.07656491, 0.11839452, 0.37448484]]])

In [28]:
np.random.randint(1,10,size=(3,3)) # it creates an array of 3x3 with random numbers from 1-10

array([[4, 1, 9],
       [1, 8, 2],
       [7, 8, 8]], dtype=int32)

In [29]:
# identiity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
one = np.ones((1,3))
r = np.repeat(one,repeats=3,axis=0) # that repeats the one array three times in different rows because axis = 0
r1 = np.repeat(one,repeats=3,axis=1) # that repeats the one array three times in same row because axis = 1
print(r)
print()
print(r1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
# Print the pattern 
'''
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
'''

'\n[[1. 1. 1. 1. 1.]\n [1. 0. 0. 0. 1.]\n [1. 0. 9. 0. 1.]\n [1. 0. 0. 0. 1.]\n [1. 1. 1. 1. 1.]]\n'

In [32]:
output  = np.ones((5,5))

zero = np.zeros((3,3))

zero[1,1] = 9
print(zero)
output[1:-1,1:-1] = zero
print()
print(output)



[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
# Copying an array
ac = np.array([1,2,3,4,5,6])
bc = np.copy(ac)
print(bc)

[1 2 3 4 5 6]


# Mathematics

In [34]:
m = np.array([1,2,3,4,5])
print(m)

[1 2 3 4 5]


In [35]:
m+2

array([3, 4, 5, 6, 7])

In [36]:
m-2

array([-1,  0,  1,  2,  3])

In [37]:
m*2

array([ 2,  4,  6,  8, 10])

In [38]:
m/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [39]:
m**2

array([ 1,  4,  9, 16, 25])

In [40]:
# sin of a num
np.sin(m)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [41]:
np.cos(m)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

# Linear Algebra

In [42]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [43]:
# Finding the determinent 
c = np.identity(3)
print(np.linalg.det(c))


1.0


Statistics

In [44]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats,axis=1)

array([1, 4])

In [46]:
np.max(stats,axis=0)

array([4, 5, 6])

In [47]:
np.mean(stats)

np.float64(3.5)

In [48]:
np.median(stats)

np.float64(3.5)

In [49]:
np.average(stats)

np.float64(3.5)

In [50]:
su = np.sum(stats,axis=1)
su

array([ 6, 15])

# Reorganizing Arrays

In [51]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print()
after = before.reshape((2,4,1))
print(after) 

[[1 2 3 4]
 [5 6 7 8]]

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


In [52]:
# Vertical Stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [53]:
# Horizontal stack
print(np.hstack([v1,v2,v1,v2]))

[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


Miscellaneous

Load Data from file

In [54]:
filedata = np.genfromtxt('Data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int32)

### Boolean masking and advanced indexing

In [59]:
filedata[filedata>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15], dtype=int32)

In [64]:
li = np.array([1,2,3,4,5])
li[[1,2,3]]

array([2, 3, 4])

In [76]:
mat = np.arange(1,31).reshape(6,5)
mat[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [75]:
mat[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [83]:
mat[[[0],[4],[5]],[[-2,-1],[-2,-1],[-2,-1]]]

array([[ 4,  5],
       [24, 25],
       [29, 30]])