# Numpy_random

In [2]:
import numpy as np

# rand

In [3]:
var=np.random.rand(2,2) # The function rand generates the random numbers b\w 0-1
print(var)

[[0.75349554 0.09073681]
 [0.7069152  0.37961919]]


# randn

In [16]:
var2 = np.random.randn(2,2) #The function rand generates the random numbers b\w 0-1 in both -ve and +ve
print(var2)

[[-0.26745662 -1.83589309]
 [ 0.26372479  1.42044658]]


# ranf

In [11]:
var3 = np.random.ranf(4) #The function rand generates the random numbers b\w (0-1)  1 is exclusive
print(var3)

[0.88169512 0.35262943 0.54371345 0.12242114]


In [33]:
var4 = np.random.randint(1,10,5)
print(var4)



[4 4 5 4 6]
