# Numpy Array

In [1]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [3]:
l = []
for i in range(1,5):
    x = int(input(f"Enter element no {i}"))
    l.append(x)
arr = np.array(l)


# ndim function

In [4]:
print(arr.ndim) # It tells the dimension of an array 

1


# 2D array

In [5]:
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar2)
print(ar2.ndim) # 2 dimension array

[[1 2 3]
 [4 5 6]]
2


# 3D array 

In [6]:
ar3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


# n-dimensional array 

In [7]:
ndarr = np.array([1,2,3],ndmin=10)
print(ndarr)
print(ndarr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


# Range(By sing arange() Function)


In [8]:
ar_zero  = np.arange(10)
print(ar_zero) # It creates an array that contains elements from zero to 9 

[0 1 2 3 4 5 6 7 8 9]
