In [1]:
import numpy as np

In [2]:
#Create a Numpy array filled with all zeros
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# Create a Numpy array filled with all ones
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Check whether a Numpy array contains a specified row
arr = np.arange(1,21).reshape(4,5)
print(arr)
print()
print([1,2,3,4,5] in arr)
print([1,3,3,4,5] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

True
False


In [ ]:
# How to check whether specified values are present in NumPy array?
n_array = np.array([[2, 3, 0],[4, 1, 6]])
print(2 in n_array)
print(5 in n_array)

True
False


In [ ]:
# Reverse a numpy array
print(n_array[[0,1],::-1])

[[0 3 2]
 [6 1 4]]
